name: Stanley-lua/File
description: File I/O wrapper for Lua.
version: 0.1
author: 
  - email: wolf2789@gmail.com
    name: Dawid Bugajski
autoload:
  - type: global
    name: File
    path: File.lua
